"""
risk_detector.py
Builds structured risks directly from ChromaDB retrieval results.
Structured fields are computed from signals, not generated by LLM.
"""

import sys, os, json, re
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")))

from rag.retriever import retrieve
from rag.llm_engine import query_llm

detector_name = "risk"

RISK_QUERIES = [
    "NVIDIA competitor threat AMD Intel GPU market share loss",
    "NVIDIA regulatory risk export control China ban sanction",
    "NVIDIA supply chain shortage chip production TSMC",
    "NVIDIA stock decline earnings miss negative forecast",
    "NVIDIA geopolitical risk government policy semiconductor",
]

RISK_KEYWORDS = [
    "risk","threat","decline","ban","shortage","lawsuit","fine","regulation",
    "competition","loss","negative","warning","concern","uncertainty","sanction",
    "restrict","drop","fall","miss","weak","cut","penalty","blocked","tariff",
]

CATEGORY_SIGNALS = {
    "Competitive":   ["amd","intel","qualcomm","competitor","market share","rival","challenge"],
    "Regulatory":    ["regulation","ban","export control","government","policy","law","restrict","sanction"],
    "Supply Chain":  ["supply","tsmc","shortage","production","manufacturing","chip","wafer"],
    "Financial":     ["stock","earnings","revenue","profit","valuation","investor","miss","decline"],
    "Geopolitical":  ["china","taiwan","us-china","geopolit","trade war","tariff","foreign"],
    "Technology":    ["technology","architecture","obsolete","competing","alternative","open source"],
    "Reputational":  ["lawsuit","controversy","scandal","criticism","public","backlash"],
}

MITIGATION_MAP = {
    "Competitive":   "Accelerate product roadmap differentiation and deepen customer lock-in through CUDA ecosystem.",
    "Regulatory":    "Engage government relations proactively and develop compliant product variants.",
    "Supply Chain":  "Diversify manufacturing partners and increase strategic inventory buffers.",
    "Financial":     "Manage investor expectations with transparent guidance and maintain margin discipline.",
    "Geopolitical":  "Expand addressable markets outside restricted regions and build domestic supply chain resilience.",
    "Technology":    "Increase R&D investment and maintain technology leadership through next-gen architecture.",
    "Reputational":  "Engage stakeholders proactively and implement governance improvements.",
}


def _infer_category(text):
    text_l = text.lower()
    scores = {cat: sum(1 for kw in kws if kw in text_l) for cat, kws in CATEGORY_SIGNALS.items()}
    best = max(scores, key=scores.get)
    return best if scores[best] > 0 else "Competitive"


def _infer_severity(sim, kw_hits):
    if sim > 0.80 or kw_hits >= 5: return "Critical"
    if sim > 0.65 or kw_hits >= 3: return "High"
    if sim > 0.50 or kw_hits >= 1: return "Medium"
    return "Low"


def _get_description(title, content):
    """Extract clean, non-duplicated description from scraped content."""
    clean = re.sub(r'\s+', ' ', content).strip()

    # Strip leading source name pattern e.g. "The Motley Fool. Title..."
    if ". " in clean[:60]:
        parts = clean.split(". ", 1)
        if len(parts[0]) < 35:
            clean = parts[1].strip()

    # Strip title from start if duplicated
    if clean.lower().startswith(title[:35].lower()):
        clean = clean[len(title):].strip().lstrip('.-– ')

    # Strip trailing " Source Name" duplication
    clean = re.sub(r'\s+[A-Z][A-Za-z\s&]{2,25}$', '', clean).strip()

    # Remove mid-text duplication: "Sentence. Same sentence again"
    if ". " in clean[30:]:
        mid = clean.find(". ", 30)
        first_half = clean[:mid].lower()
        second_half = clean[mid+2:].lower()
        if second_half.startswith(first_half[:20]):
            clean = clean[:mid+1]

    clean = clean.strip()

    if len(clean) < 40:
        title_l = title.lower()
        if any(w in title_l for w in ["china", "ban", "export", "sanction", "restrict"]):
            return "Export controls and geopolitical restrictions pose a material revenue risk by limiting NVIDIA's access to major markets."
        elif any(w in title_l for w in ["competitor", "amd", "intel", "qualcomm", "threat", "challenge"]):
            return "Intensifying competitive pressure from established players threatens NVIDIA's GPU market share and pricing power."
        elif any(w in title_l for w in ["customer", "supply", "shortage", "concentration"]):
            return "Customer concentration and supply chain dependencies create structural vulnerabilities in NVIDIA's business model."
        elif any(w in title_l for w in ["laptop", "cpu", "market", "enter"]):
            return "NVIDIA's expansion into new hardware segments intensifies competitive dynamics and could pressure incumbent relationships."
        else:
            return "This signal warrants executive attention as it could materially impact NVIDIA's strategic positioning or financial performance."

    return clean[:280] + ("…" if len(clean) > 280 else "")




EVIDENCE_NOISE = [
    "my garage", "making me", "$/hr", "&#x27;", "&#x2f;",
    "in all seriousness", "running in my", "show hn", "ask hn",
    "pytorch on java", "smile-deep", "jvm",
]

def _is_clean(text):
    t = text.lower()
    return not any(n in t for n in EVIDENCE_NOISE) and len(text) > 30

def _clean_title(t):
    import re
    t = re.sub(r"(\w)'\s", r"\1's ", t)
    t = re.sub(r"(\w)'$", r"\1's", t)
    t = re.sub(r'\s[-–]\s[A-Z][A-Za-z\s&\.]{2,35}\.\.\.$', '', t).strip()
    t = re.sub(r'\s[-–]\s[A-Z][A-Za-z\s&]{2,30}$', '', t).strip()
    return t.strip('…').strip()

def detect_risks(n_per_query=6, top_n=5):
    print("[risk_detector] Detecting risks...")

    candidates = {}
    for q in RISK_QUERIES:
        for doc in retrieve(q, n_results=n_per_query, use_hybrid=True):
            did = doc["id"]
            if did not in candidates or doc["similarity"] > candidates[did]["similarity"]:
                candidates[did] = doc

    if not candidates:
        return _fallback_risks()

    scored = []
    for doc in candidates.values():
        text = doc["content"].lower()
        kw_hits = sum(1 for kw in RISK_KEYWORDS if kw in text)
        doc["_kw_hits"] = kw_hits
        doc["_total_score"] = round(doc["similarity"] * 2 + kw_hits * 0.3, 3)
        scored.append(doc)

    scored.sort(key=lambda d: d["_total_score"], reverse=True)
    top_docs = scored[:top_n]

    results = []
    for doc in top_docs:
        title   = doc["metadata"].get("title", doc["content"][:70])
        title   = _clean_title(re.sub(r'\s[-–]\s[A-Z][^-–]{2,40}$', '', title).strip())
        content = doc["content"]
        sim     = doc["similarity"]
        kw_hits = doc["_kw_hits"]

        category = _infer_category(content)
        severity = _infer_severity(sim, kw_hits)
        conf     = round(min(sim + kw_hits * 0.03, 0.97), 2)

        sentences = re.split(r'(?<=[.!?])\s+', content)
        ev_raw = [s.strip() for s in sentences if any(kw in s.lower() for kw in RISK_KEYWORDS) and _is_clean(s)]
        seen = set()
        evidence = []
        for e in ev_raw:
            key = e[:40].lower()
            if key not in seen and len(e) > 20:
                seen.add(key)
                evidence.append(e)
                if len(evidence) >= 2: break
        if not evidence:
            evidence = [content[:180]]

        desc = _get_description(title, content)

        results.append({
            "title":            title[:120],
            "description":      desc,
            "category":         category,
            "severity_level":   severity,
            "confidence_score": conf,
            "evidence":         evidence,
            "mitigation":       MITIGATION_MAP.get(category, "Monitor closely and adjust strategy accordingly."),
            "url":              doc["metadata"].get("url", ""),
        })

    print(f"[risk_detector] Found {len(results)} risks")
    return results


def _fallback_risks():
    return [{"title":"No data available","description":"Run scrapers and embeddings first.","category":"N/A","severity_level":"Low","confidence_score":0.0,"evidence":[],"mitigation":"Collect data."}]


if __name__ == "__main__":
    print(json.dumps(detect_risks(), indent=2))
